"""one running run per conversation

Revision ID: 6b27af76a38a
Revises: 29f302f66e10
Create Date: 2026-09-24 08:45:15.111435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b27af76a38a'
down_revision: Union[str, Sequence[str], None] = '29f302f66e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index('uq_one_running_run_per_conversation', ['conversation_id'], unique=True, sqlite_where=sa.text("status = 'running'"), postgresql_where=sa.text("status = 'running'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index('uq_one_running_run_per_conversation', sqlite_where=sa.text("status = 'running'"), postgresql_where=sa.text("status = 'running'"))

    # ### end Alembic commands ###
